#!/bin/bash
# =================================================================
# 🚀 OG SİPARİŞ - HOSTINGER VPS DEPLOYMENT SCRIPT
# Generated by Hostinger API Deployment Tool
# =================================================================

set -e

echo "🚀 OG Sipariş Deployment Başlıyor..."

dnf update -y

dnf install -y curl wget git postgresql postgresql-server postgresql-contrib

curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -

dnf install -y nodejs

npm install -g pm2

postgresql-setup --initdb

systemctl enable postgresql

systemctl start postgresql

sudo -u postgres psql -c "CREATE DATABASE ogformdb;"

sudo -u postgres psql -c "CREATE USER ogform WITH ENCRYPTED PASSWORD '91drgws5v6t';"

sudo -u postgres psql -c "ALTER ROLE ogform SET client_encoding TO 'utf8';"

sudo -u postgres psql -c "ALTER ROLE ogform SET default_transaction_isolation TO 'read committed';"

sudo -u postgres psql -c "ALTER ROLE ogform SET timezone TO 'UTC';"

sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ogformdb TO ogform;"

mkdir -p /home/ogsiparis.com/public_html/backend

cd /home/ogsiparis.com/public_html/backend

git clone https://github.com/MehmetEminSelek/ogBackend.git .

npm install

cat > .env << 'EOF'
NODE_ENV=production
PORT=3000
DATABASE_URL="postgresql://ogform:91drgws5v6t@localhost:5432/ogformdb?schema=public"
JWT_SECRET="og-siparis-super-secret-jwt-key-production-$(date +%s)"
NEXT_PUBLIC_API_URL=https://ogsiparis.com/api
CORS_ORIGIN=https://ogsiparis.com
SMTP_HOST=smtp.hostinger.com
SMTP_PORT=587
SMTP_USER=admin@ogsiparis.com
SMTP_PASS=your-email-password
MAX_FILE_SIZE=10MB
UPLOAD_DIR=./uploads
BCRYPT_ROUNDS=12
EOF

npx prisma generate

npx prisma db push

npm run build

mkdir -p /home/ogsiparis.com/public_html/frontend

cd /home/ogsiparis.com/public_html/frontend

git clone https://github.com/MehmetEminSelek/ogFrontend.git .

npm install

cat > .env.production << 'EOF'
NEXT_PUBLIC_API_URL=https://ogsiparis.com/api
NEXT_PUBLIC_SITE_URL=https://ogsiparis.com
NODE_ENV=production
EOF

npm run build

cd /home/ogsiparis.com/public_html/backend

pm2 start npm --name "og-backend" -- start

cd /home/ogsiparis.com/public_html/frontend

pm2 start npm --name "og-frontend" -- start -- -p 5173

pm2 save

pm2 startup

firewall-cmd --permanent --add-service=http

firewall-cmd --permanent --add-service=https

firewall-cmd --permanent --add-port=3000/tcp

firewall-cmd --permanent --add-port=5173/tcp

firewall-cmd --reload

echo ""
echo "🎉 DEPLOYMENT TAMAMLANDI!"
echo "🌐 Website: https://ogsiparis.com"
echo "🔗 API: https://ogsiparis.com/api"
echo "🎛️ CyberPanel: https://147.93.123.161:8090"
echo ""
echo "📊 PM2 durumu kontrol edin: pm2 list"
echo "📜 PM2 logları: pm2 logs"
echo ""
echo "✅ Siteniz hazır: https://ogsiparis.com"
